user nobody;

error_log /Users/ivan/Desktop/prog/2026-MAI-Backend-I-Lyapin/lesson-02/logs/error.log info;
pid /Users/ivan/Desktop/prog/2026-MAI-Backend-I-Lyapin/lesson-02/nginx.pid;

worker_processes 2;

events {
    worker_connections 1024;
}

http {
    access_log /Users/ivan/Desktop/prog/2026-MAI-Backend-I-Lyapin/lesson-02/logs/access.log;
    log_format simple '$remote_addr $request $status';

    upstream gunicorn_upstream {
        server 127.0.0.1:8000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name localhost;

        location /public/ {
            alias /Users/ivan/Desktop/prog/2026-MAI-Backend-I-Lyapin/lesson-02/public/;
            autoindex on;
            expires 1h;
        }

        location /gunicorn/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_pass http://gunicorn_upstream;
        }
    }
}
