# Generated by Django 5.0 on 2026-04-28 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_actor_movie_description_movie_favorited_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="added_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата добавления"
            ),
        ),
    ]
